controller_joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']

nj_220_2_7:
  sample_period: 1.0e-3

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250

  robust_inverse_dynamics:
    type: robot_control/RobustInverseDynamicsControl
    base_frame: world
    tool_frame: flange
    setpoint_topic_name: "/nj_220_2_7/joint_target"
    natural_frequency: 100   # natural frequency of the closed loop
    damping: 1              # relative damping of the closed loop
    robustness_gain: 0.01   # robustness gain
    integral_gain: [0.01, 0.01, 0.01, 0.01, 0.01, 0.0001]

  position_joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10000.0, i: 1, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10000.0, i: 1, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 10000.0, i: 10, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 10000.0, i: 1, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10000.0, i: 1, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 10000.0, i: 1, d: 10.0}


  # position_joint_trajectory_controller:
  #   type: "position_controllers/JointPositionController"
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6

  # gazebo_ros_control:
  #   pid_gains:
  #     joint_1:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
  #     joint_2:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
  #     joint_3:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
  #     joint_4:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
  #     joint_5:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
  #     joint_6:
  #       p: 1000.0
  #       i: 0.1
  #       d: 10.0
